### ISSUE TITLE
Feature Request: Document prometheus-operator and istio-installer

### ISSUE THREAD

**Issue by StevenACoffman** [istio-ecosystem/istio-installer#18]
Our use case for istio-installer is to install and upgrade istio components separate from  prometheus-operatror. While istio/istio#7352 made this possible, it is not well advertised or documented.

In case someone else is looking for a similar setup, here's how to befriend Istio with mTLS and Prometheus deployed via prometheus-operator:

1. When deploying `prometheus-operator`, extend `prometheusSpec.secrets` with `istio.default` secret, this gets Istio's certificates mounted inside Prometheus pod under `/etc/prometheus/secrets/`.
see this: https://github.com/helm/charts/blob/08c82581a13ddc1409fffdd22dbc2c90db738c95/stable/prometheus-operator/values.yaml#L783-L788
 
Change it to this:
 
```
secrets:
  - istio.default
```

2. In the `ServiceMonitor` object use `https` scheme and point Prometheus to Istio's certificates like so:
```
endpoints:
  - port: http
    interval: 15s
    honorLabels: true
    path: "/api/health/prometheus"
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/secrets/istio.default/root-cert.pem
      certFile: /etc/prometheus/secrets/istio.default/cert-chain.pem
      keyFile: /etc/prometheus/secrets/istio.default/key.pem
      insecureSkipVerify: true
```
